# Site settings
title: "Rambod Mojgani| CV"
description: "|..."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Rambod Mojgani"
resume_title:                   "Machine Learning Research Engineer at RTX Corporation" #Postdoctoral Scholar at the University of Chicago" #Postdoctoral Research Associate at Rice University"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "rm99[we can beat the crawlers]uchicago.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "555-7334"
resume_contact_address:         "104 S Wright St
				Urbana, IL-61801"

resume_header_contact_info:     " ✉ mojgani2[we can beat the crawlers]@illinois.edu"
display_header_contact_info:    "true"

resume_header_intro: "<p> ■ computational physics ■ data-driven modeling ■ machine learning in physical systems ■ dimensionality reduction </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/rmojgani"
  resume_twitter_url:           "http://twitter.com/rmojgani1" 
#  resume_dribbble_url:          "https://scholar.google.com/citations?user=AWF32UEAAAAJ&hl=en&oi=ao" # Faking google scholar
#  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/rmojgani"
#  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://rmojgani.com"
  resume_gscholar_url:          "https://scholar.google.com/citations?user=AWF32UEAAAAJ&hl=en&oi=ao"
#  resume_medium_url:            "https://medium.com/@jglovier"
  resume_youtube_url:            "https://www.youtube.com/rmojgani"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

  #gems:
plugins:
  - jekyll-seo-tag

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
